server.port=8080
spring.devtools.restart.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=postgres
spring.datasource.password=Mentalist1986

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
hibernate.format_sql=true
